1. Fit and Transform Separately

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from pandas import DataFrame

text_data  = [ "GFG is providing a new Deep Learning Course which is really good",
               "We will be studying Deep Learning from today",
               "I want a Deep sleep today"]

vec = CountVectorizer()
vec = vec.fit(text_data)

data_transformed = vec.transform(text_data)

df = DataFrame(data_transformed.toarray(), columns = vec.vocabulary_)
df

,gfg,is,providing,new,deep,learning,course,which,really,good,we,will,be,studying,from,today,want,sleep
0,0,1,1,0,1,1,2,1,1,1,1,0,0,0,0,0,1,0
1,1,0,1,1,0,0,0,1,0,0,0,0,1,1,0,1,0,1
2,0,0,1,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0

2. Fit and Transform Combined

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from pandas import DataFrame

text_data  = [ "GFG is providing a new Deep Learning Course which is really good",
               "We will be studying Deep Learning from today",
               "I want a Deep sleep today",
               'We will be studying Deep Learning']

vec = CountVectorizer()

data_transformed = vec.fit_transform(text_data)

df = DataFrame(data_transformed.toarray(), columns = vec.vocabulary_)
df

,gfg,is,providing,new,deep,learning,course,which,really,good,we,will,be,studying,from,today,want,sleep
0,0,1,1,0,1,1,2,1,1,1,1,0,0,0,0,0,1,0
1,1,0,1,1,0,0,0,1,0,0,0,0,1,1,0,1,0,1
2,0,0,1,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0
3,1,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1

3. Dealing with Stop Words

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
from pandas import DataFrame

text_data  = [ "GFG is providing a new Deep Learning Course which is really good",
               "We will be studying Deep Learning from today",
               "I want a Deep sleep today"]

vec = CountVectorizer(stop_words = 'english', lowercase = True)
vec = vec.fit(text_data)

data_transformed = vec.transform(text_data)

df = DataFrame(data_transformed.toarray(), columns = vec.vocabulary_)
df

,gfg,providing,new,deep,learning,course,really,good,studying,today,want,sleep
0,1,1,1,1,1,1,1,1,0,0,0,0
1,0,1,0,0,1,0,0,0,0,1,1,0
2,0,1,0,0,0,0,0,0,1,0,1,1

4. Dealing with N-Gram

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
from pandas import DataFrame

text_data  = [ "GFG is providing a new Deep Learning Course which is really good",
               "We will be studying Deep Learning from today",
               "I want a Deep sleep today"]

vec = CountVectorizer(ngram_range = (3,3))
vec = vec.fit(text_data)

data_transformed = vec.transform(text_data)

df = DataFrame(data_transformed.toarray(), columns = vec.vocabulary_)
df

,gfg is providing,is providing new,providing new deep,new deep learning,deep learning course,learning course which,course which is,which is really,is really good,we will be,will be studying,be studying deep,studying deep learning,deep learning from,learning from today,want deep sleep,deep sleep today
0,0,1,1,0,0,1,1,1,1,0,1,1,0,0,0,1,0
1,1,0,0,1,0,0,0,0,0,1,0,0,1,0,1,0,1
2,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0

5. Count Vectorizer with Data Preprocessing

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
from pandas import DataFrame

text_data  = [ "GFG is providing a new Deep Learning Course which is really good",
               "We will be studying Deep Learning from today",
               "I want a Deep sleep today"]

vec = CountVectorizer(ngram_range = (1,1), stop_words = 'english', lowercase = True)
vec = vec.fit(text_data)

data_transformed = vec.transform(text_data)

df = DataFrame(data_transformed.toarray(), columns = vec.vocabulary_)
df

,gfg,providing,new,deep,learning,course,really,good,studying,today,want,sleep
0,1,1,1,1,1,1,1,1,0,0,0,0
1,0,1,0,0,1,0,0,0,0,1,1,0
2,0,1,0,0,0,0,0,0,1,0,1,1