In [1]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords
import re
import pandas as pd

In [2]:
data = pd.read_csv("tripadvisor_hotel_reviews.csv") # the data should be in the same folder as your notebook

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  109 non-null    object
 1   Rating  109 non-null    int64
dtypes: int64(1), object(1)
memory usage: 1.8+ KB

In [4]:
data.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [43]:
data['Review'][1]

'ok nothing special charge diamond member hilton decided chain shot 20th anniversary seattle, start booked suite paid extra website description not, suite bedroom bathroom standard hotel room, took printed reservation desk showed said things like tv couch ect desk clerk told oh mixed suites description kimpton website sorry free breakfast, got kidding, embassy suits sitting room bathroom bedroom unlike kimpton calls suite, 5 day stay offer correct false advertising, send kimpton preferred guest website email asking failure provide suite advertised website reservation description furnished hard copy reservation printout website desk manager duty did not reply solution, send email trip guest survey did not follow email mail, guess tell concerned guest.the staff ranged indifferent not helpful, asked desk good breakfast spots neighborhood hood told no hotels, gee best breakfast spots seattle 1/2 block away convenient hotel does not know exist, arrived late night 11 pm inside run bellman busy chating cell phone help bags.prior arrival emailed hotel inform 20th anniversary half really picky wanted make sure good, got nice email saying like deliver bottle champagne chocolate covered strawberries room arrival celebrate, told needed foam pillows, arrival no champagne strawberries no foam pillows great room view alley high rise building good not better housekeeping staff cleaner room property, impressed left morning shopping room got short trips 2 hours, beds comfortable.not good ac-heat control 4 x 4 inch screen bring green shine directly eyes night, light sensitive tape controls.this not 4 start hotel clean business hotel super high rates, better chain hotels seattle,  '

In [46]:
review_sample = data['Review'][1].lower() # Get the review and lowercase it
words_in_review = word_tokenize(review_sample) # Tokenize the review into words

# Now, iterate through the words to check against the already defined `en_stopwords` list
print("Stopwords found in the second review:")
for word in words_in_review:
  if word in en_stopwords:
    print(word)

Stopwords found in the second review:
did
did
no
does
no
no

In [6]:
data['review_lowercase'] = data['Review'].str.lower()

In [7]:
data.head()

,Review,Rating,review_lowercase
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso..."

In [9]:
nltk.download('stopwords')
en_stopwords = stopwords.words('english')
en_stopwords.remove("not")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [10]:
data['review_no_stopwords'] = data['review_lowercase'] \
                                .apply(lambda x: ' ' \
                                .join([word for word \
                                in x.split() if word \
                                not in (en_stopwords)]))

In [17]:
data['review_no_stopwords'][1]

'ok nothing special charge diamond member hilton decided chain shot 20th anniversary seattle, start booked suite paid extra website description not, suite bedroom bathroom standard hotel room, took printed reservation desk showed said things like tv couch ect desk clerk told oh mixed suites description kimpton website sorry free breakfast, got kidding, embassy suits sitting room bathroom bedroom unlike kimpton calls suite, 5 day stay offer correct false advertising, send kimpton preferred guest website email asking failure provide suite advertised website reservation description furnished hard copy reservation printout website desk manager duty not reply solution, send email trip guest survey not follow email mail, guess tell concerned guest.the staff ranged indifferent not helpful, asked desk good breakfast spots neighborhood hood told hotels, gee best breakfast spots seattle 1/2 block away convenient hotel not know exist, arrived late night 11 pm inside run bellman busy chating cell phone help bags.prior arrival emailed hotel inform 20th anniversary half really picky wanted make sure good, got nice email saying like deliver bottle champagne chocolate covered strawberries room arrival celebrate, told needed foam pillows, arrival champagne strawberries foam pillows great room view alley high rise building good not better housekeeping staff cleaner room property, impressed left morning shopping room got short trips 2 hours, beds comfortable.not good ac-heat control 4 x 4 inch screen bring green shine directly eyes night, light sensitive tape controls.this not 4 start hotel clean business hotel super high rates, better chain hotels seattle,'

In [18]:
data.head()

,Review,Rating,review_lowercase,review_no_stopwords,review_no_stopwords_no_punct
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4star experience hotel monaco s...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso..."

In [19]:
data['review_no_stopwords'][1]

'ok nothing special charge diamond member hilton decided chain shot 20th anniversary seattle, start booked suite paid extra website description not, suite bedroom bathroom standard hotel room, took printed reservation desk showed said things like tv couch ect desk clerk told oh mixed suites description kimpton website sorry free breakfast, got kidding, embassy suits sitting room bathroom bedroom unlike kimpton calls suite, 5 day stay offer correct false advertising, send kimpton preferred guest website email asking failure provide suite advertised website reservation description furnished hard copy reservation printout website desk manager duty not reply solution, send email trip guest survey not follow email mail, guess tell concerned guest.the staff ranged indifferent not helpful, asked desk good breakfast spots neighborhood hood told hotels, gee best breakfast spots seattle 1/2 block away convenient hotel not know exist, arrived late night 11 pm inside run bellman busy chating cell phone help bags.prior arrival emailed hotel inform 20th anniversary half really picky wanted make sure good, got nice email saying like deliver bottle champagne chocolate covered strawberries room arrival celebrate, told needed foam pillows, arrival champagne strawberries foam pillows great room view alley high rise building good not better housekeeping staff cleaner room property, impressed left morning shopping room got short trips 2 hours, beds comfortable.not good ac-heat control 4 x 4 inch screen bring green shine directly eyes night, light sensitive tape controls.this not 4 start hotel clean business hotel super high rates, better chain hotels seattle,'

In [20]:
data['review_no_stopwords_no_punct'] = data \
                                    .apply(lambda x: \
                                    re.sub(r"[*]", \
                                    "star", \
                                    x['review_no_stopwords'] \
                                    ), axis=1)

In [22]:
data.head()

,Review,Rating,review_lowercase,review_no_stopwords,review_no_stopwords_no_punct
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4star experience hotel monaco s...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso..."

In [ ]:
Tokenizing

# Tokenizing

In [25]:
nltk.download('punkt')
nltk.download('punkt_tab')
data['tokenized'] = data.apply(lambda x: \
                               word_tokenize( \
                               x['review_no_stopwords_no_punct'] \
                               ), axis=1)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [26]:
data['tokenized'][1]

['ok',
 'nothing',
 'special',
 'charge',
 'diamond',
 'member',
 'hilton',
 'decided',
 'chain',
 'shot',
 '20th',
 'anniversary',
 'seattle',
 ',',
 'start',
 'booked',
 'suite',
 'paid',
 'extra',
 'website',
 'description',
 'not',
 ',',
 'suite',
 'bedroom',
 'bathroom',
 'standard',
 'hotel',
 'room',
 ',',
 'took',
 'printed',
 'reservation',
 'desk',
 'showed',
 'said',
 'things',
 'like',
 'tv',
 'couch',
 'ect',
 'desk',
 'clerk',
 'told',
 'oh',
 'mixed',
 'suites',
 'description',
 'kimpton',
 'website',
 'sorry',
 'free',
 'breakfast',
 ',',
 'got',
 'kidding',
 ',',
 'embassy',
 'suits',
 'sitting',
 'room',
 'bathroom',
 'bedroom',
 'unlike',
 'kimpton',
 'calls',
 'suite',
 ',',
 '5',
 'day',
 'stay',
 'offer',
 'correct',
 'false',
 'advertising',
 ',',
 'send',
 'kimpton',
 'preferred',
 'guest',
 'website',
 'email',
 'asking',
 'failure',
 'provide',
 'suite',
 'advertised',
 'website',
 'reservation',
 'description',
 'furnished',
 'hard',
 'copy',
 'reservation',
 'printout',
 'website',
 'desk',
 'manager',
 'duty',
 'not',
 'reply',
 'solution',
 ',',
 'send',
 'email',
 'trip',
 'guest',
 'survey',
 'not',
 'follow',
 'email',
 'mail',
 ',',
 'guess',
 'tell',
 'concerned',
 'guest.the',
 'staff',
 'ranged',
 'indifferent',
 'not',
 'helpful',
 ',',
 'asked',
 'desk',
 'good',
 'breakfast',
 'spots',
 'neighborhood',
 'hood',
 'told',
 'hotels',
 ',',
 'gee',
 'best',
 'breakfast',
 'spots',
 'seattle',
 '1/2',
 'block',
 'away',
 'convenient',
 'hotel',
 'not',
 'know',
 'exist',
 ',',
 'arrived',
 'late',
 'night',
 '11',
 'pm',
 'inside',
 'run',
 'bellman',
 'busy',
 'chating',
 'cell',
 'phone',
 'help',
 'bags.prior',
 'arrival',
 'emailed',
 'hotel',
 'inform',
 '20th',
 'anniversary',
 'half',
 'really',
 'picky',
 'wanted',
 'make',
 'sure',
 'good',
 ',',
 'got',
 'nice',
 'email',
 'saying',
 'like',
 'deliver',
 'bottle',
 'champagne',
 'chocolate',
 'covered',
 'strawberries',
 'room',
 'arrival',
 'celebrate',
 ',',
 'told',
 'needed',
 'foam',
 'pillows',
 ',',
 'arrival',
 'champagne',
 'strawberries',
 'foam',
 'pillows',
 'great',
 'room',
 'view',
 'alley',
 'high',
 'rise',
 'building',
 'good',
 'not',
 'better',
 'housekeeping',
 'staff',
 'cleaner',
 'room',
 'property',
 ',',
 'impressed',
 'left',
 'morning',
 'shopping',
 'room',
 'got',
 'short',
 'trips',
 '2',
 'hours',
 ',',
 'beds',
 'comfortable.not',
 'good',
 'ac-heat',
 'control',
 '4',
 'x',
 '4',
 'inch',
 'screen',
 'bring',
 'green',
 'shine',
 'directly',
 'eyes',
 'night',
 ',',
 'light',
 'sensitive',
 'tape',
 'controls.this',
 'not',
 '4',
 'start',
 'hotel',
 'clean',
 'business',
 'hotel',
 'super',
 'high',
 'rates',
 ',',
 'better',
 'chain',
 'hotels',
 'seattle',
 ',']

In [27]:
##Stemming

In [29]:
ps = PorterStemmer()
data["stemmed"] = data["tokenized"] \
                  .apply(lambda tokens: \
                  [ps.stem(token) \
                   for token in tokens])

In [30]:
data.head()

,Review,Rating,review_lowercase,review_no_stopwords,review_no_stopwords_no_punct,tokenized,stemmed
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d...","[nice, hotel, expens, park, got, good, deal, s..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member...","[ok, noth, special, charg, diamond, member, hi..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4star experience hotel monaco s...,"[nice, rooms, not, 4star, experience, hotel, m...","[nice, room, not, 4star, experi, hotel, monaco..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...","[unique, ,, great, stay, ,, wonderful, time, h...","[uniqu, ,, great, stay, ,, wonder, time, hotel..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...","[great, stay, great, stay, ,, went, seahawk, g...","[great, stay, great, stay, ,, went, seahawk, g..."

In [32]:
data['stemmed'][1]

['ok',
 'noth',
 'special',
 'charg',
 'diamond',
 'member',
 'hilton',
 'decid',
 'chain',
 'shot',
 '20th',
 'anniversari',
 'seattl',
 ',',
 'start',
 'book',
 'suit',
 'paid',
 'extra',
 'websit',
 'descript',
 'not',
 ',',
 'suit',
 'bedroom',
 'bathroom',
 'standard',
 'hotel',
 'room',
 ',',
 'took',
 'print',
 'reserv',
 'desk',
 'show',
 'said',
 'thing',
 'like',
 'tv',
 'couch',
 'ect',
 'desk',
 'clerk',
 'told',
 'oh',
 'mix',
 'suit',
 'descript',
 'kimpton',
 'websit',
 'sorri',
 'free',
 'breakfast',
 ',',
 'got',
 'kid',
 ',',
 'embassi',
 'suit',
 'sit',
 'room',
 'bathroom',
 'bedroom',
 'unlik',
 'kimpton',
 'call',
 'suit',
 ',',
 '5',
 'day',
 'stay',
 'offer',
 'correct',
 'fals',
 'advertis',
 ',',
 'send',
 'kimpton',
 'prefer',
 'guest',
 'websit',
 'email',
 'ask',
 'failur',
 'provid',
 'suit',
 'advertis',
 'websit',
 'reserv',
 'descript',
 'furnish',
 'hard',
 'copi',
 'reserv',
 'printout',
 'websit',
 'desk',
 'manag',
 'duti',
 'not',
 'repli',
 'solut',
 ',',
 'send',
 'email',
 'trip',
 'guest',
 'survey',
 'not',
 'follow',
 'email',
 'mail',
 ',',
 'guess',
 'tell',
 'concern',
 'guest.th',
 'staff',
 'rang',
 'indiffer',
 'not',
 'help',
 ',',
 'ask',
 'desk',
 'good',
 'breakfast',
 'spot',
 'neighborhood',
 'hood',
 'told',
 'hotel',
 ',',
 'gee',
 'best',
 'breakfast',
 'spot',
 'seattl',
 '1/2',
 'block',
 'away',
 'conveni',
 'hotel',
 'not',
 'know',
 'exist',
 ',',
 'arriv',
 'late',
 'night',
 '11',
 'pm',
 'insid',
 'run',
 'bellman',
 'busi',
 'chate',
 'cell',
 'phone',
 'help',
 'bags.prior',
 'arriv',
 'email',
 'hotel',
 'inform',
 '20th',
 'anniversari',
 'half',
 'realli',
 'picki',
 'want',
 'make',
 'sure',
 'good',
 ',',
 'got',
 'nice',
 'email',
 'say',
 'like',
 'deliv',
 'bottl',
 'champagn',
 'chocol',
 'cover',
 'strawberri',
 'room',
 'arriv',
 'celebr',
 ',',
 'told',
 'need',
 'foam',
 'pillow',
 ',',
 'arriv',
 'champagn',
 'strawberri',
 'foam',
 'pillow',
 'great',
 'room',
 'view',
 'alley',
 'high',
 'rise',
 'build',
 'good',
 'not',
 'better',
 'housekeep',
 'staff',
 'cleaner',
 'room',
 'properti',
 ',',
 'impress',
 'left',
 'morn',
 'shop',
 'room',
 'got',
 'short',
 'trip',
 '2',
 'hour',
 ',',
 'bed',
 'comfortable.not',
 'good',
 'ac-heat',
 'control',
 '4',
 'x',
 '4',
 'inch',
 'screen',
 'bring',
 'green',
 'shine',
 'directli',
 'eye',
 'night',
 ',',
 'light',
 'sensit',
 'tape',
 'controls.thi',
 'not',
 '4',
 'start',
 'hotel',
 'clean',
 'busi',
 'hotel',
 'super',
 'high',
 'rate',
 ',',
 'better',
 'chain',
 'hotel',
 'seattl',
 ',']

In [33]:
##Lemmatization

In [34]:
lemmatizer = WordNetLemmatizer()

In [36]:
nltk.download('wordnet')
data["lemmatized"] = data["tokenized"] \
                    .apply(lambda tokens: \
                    [lemmatizer.lemmatize(token) \
                     for token in tokens])

[nltk_data] Downloading package wordnet to /root/nltk_data...

In [37]:
data['lemmatized'][1]

['ok',
 'nothing',
 'special',
 'charge',
 'diamond',
 'member',
 'hilton',
 'decided',
 'chain',
 'shot',
 '20th',
 'anniversary',
 'seattle',
 ',',
 'start',
 'booked',
 'suite',
 'paid',
 'extra',
 'website',
 'description',
 'not',
 ',',
 'suite',
 'bedroom',
 'bathroom',
 'standard',
 'hotel',
 'room',
 ',',
 'took',
 'printed',
 'reservation',
 'desk',
 'showed',
 'said',
 'thing',
 'like',
 'tv',
 'couch',
 'ect',
 'desk',
 'clerk',
 'told',
 'oh',
 'mixed',
 'suite',
 'description',
 'kimpton',
 'website',
 'sorry',
 'free',
 'breakfast',
 ',',
 'got',
 'kidding',
 ',',
 'embassy',
 'suit',
 'sitting',
 'room',
 'bathroom',
 'bedroom',
 'unlike',
 'kimpton',
 'call',
 'suite',
 ',',
 '5',
 'day',
 'stay',
 'offer',
 'correct',
 'false',
 'advertising',
 ',',
 'send',
 'kimpton',
 'preferred',
 'guest',
 'website',
 'email',
 'asking',
 'failure',
 'provide',
 'suite',
 'advertised',
 'website',
 'reservation',
 'description',
 'furnished',
 'hard',
 'copy',
 'reservation',
 'printout',
 'website',
 'desk',
 'manager',
 'duty',
 'not',
 'reply',
 'solution',
 ',',
 'send',
 'email',
 'trip',
 'guest',
 'survey',
 'not',
 'follow',
 'email',
 'mail',
 ',',
 'guess',
 'tell',
 'concerned',
 'guest.the',
 'staff',
 'ranged',
 'indifferent',
 'not',
 'helpful',
 ',',
 'asked',
 'desk',
 'good',
 'breakfast',
 'spot',
 'neighborhood',
 'hood',
 'told',
 'hotel',
 ',',
 'gee',
 'best',
 'breakfast',
 'spot',
 'seattle',
 '1/2',
 'block',
 'away',
 'convenient',
 'hotel',
 'not',
 'know',
 'exist',
 ',',
 'arrived',
 'late',
 'night',
 '11',
 'pm',
 'inside',
 'run',
 'bellman',
 'busy',
 'chating',
 'cell',
 'phone',
 'help',
 'bags.prior',
 'arrival',
 'emailed',
 'hotel',
 'inform',
 '20th',
 'anniversary',
 'half',
 'really',
 'picky',
 'wanted',
 'make',
 'sure',
 'good',
 ',',
 'got',
 'nice',
 'email',
 'saying',
 'like',
 'deliver',
 'bottle',
 'champagne',
 'chocolate',
 'covered',
 'strawberry',
 'room',
 'arrival',
 'celebrate',
 ',',
 'told',
 'needed',
 'foam',
 'pillow',
 ',',
 'arrival',
 'champagne',
 'strawberry',
 'foam',
 'pillow',
 'great',
 'room',
 'view',
 'alley',
 'high',
 'rise',
 'building',
 'good',
 'not',
 'better',
 'housekeeping',
 'staff',
 'cleaner',
 'room',
 'property',
 ',',
 'impressed',
 'left',
 'morning',
 'shopping',
 'room',
 'got',
 'short',
 'trip',
 '2',
 'hour',
 ',',
 'bed',
 'comfortable.not',
 'good',
 'ac-heat',
 'control',
 '4',
 'x',
 '4',
 'inch',
 'screen',
 'bring',
 'green',
 'shine',
 'directly',
 'eye',
 'night',
 ',',
 'light',
 'sensitive',
 'tape',
 'controls.this',
 'not',
 '4',
 'start',
 'hotel',
 'clean',
 'business',
 'hotel',
 'super',
 'high',
 'rate',
 ',',
 'better',
 'chain',
 'hotel',
 'seattle',
 ',']

In [38]:
data.head()

,Review,Rating,review_lowercase,review_no_stopwords,review_no_stopwords_no_punct,tokenized,stemmed,lemmatized
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d...","[nice, hotel, expens, park, got, good, deal, s...","[nice, hotel, expensive, parking, got, good, d..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member...","[ok, noth, special, charg, diamond, member, hi...","[ok, nothing, special, charge, diamond, member..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4star experience hotel monaco s...,"[nice, rooms, not, 4star, experience, hotel, m...","[nice, room, not, 4star, experi, hotel, monaco...","[nice, room, not, 4star, experience, hotel, mo..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...","[unique, ,, great, stay, ,, wonderful, time, h...","[uniqu, ,, great, stay, ,, wonder, time, hotel...","[unique, ,, great, stay, ,, wonderful, time, h..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...","[great, stay, great, stay, ,, went, seahawk, g...","[great, stay, great, stay, ,, went, seahawk, g...","[great, stay, great, stay, ,, went, seahawk, g..."

In [39]:
##N-grams

In [40]:
tokens_clean = sum(data['lemmatized'], [])
# unigrams: n=1
unigrams = (pd.Series \
            (nltk.ngrams(tokens_clean, 1)) \
            .value_counts())
print(unigrams)

(,,)                 1094
(hotel,)              292
(room,)               275
(great,)              126
(not,)                122
                     ...
(hole,)                 1
(needsattention,)       1
(truly,)                1
(courtesy,)             1
(austin,)               1
Name: count, Length: 2634, dtype: int64

In [41]:
# bigrams: n=2
bigrams = (pd.Series \
           (nltk.ngrams(tokens_clean, 2)) \
           .value_counts())
print(bigrams)

(,, room)                   55
(hotel, ,)                  41
(,, great)                  41
(room, ,)                   37
(,, hotel)                  31
                            ..
(warwick, changed)           1
(dissapointment, trip)       1
(hotel, dissapointment)      1
(unfortunately, warwick)     1
(intruder, ,)                1
Name: count, Length: 8411, dtype: int64

In [42]:
ngrams_4 = (pd.Series \
            (nltk.ngrams(tokens_clean, 4)) \
            .value_counts())
print(ngrams_4)

(pike, place, market, ,)              4
(staff, friendly, helpful, ,)         3
(room, really, comfortable, clean)    2
(nice, view, space, needle)           2
(,, staff, friendly, helpful)         2
                                     ..
(hotel, dissapointment, trip, ,)      1
(dissapointment, trip, ,, 3)          1
(trip, ,, 3, night)                   1
(,, 3, night, stay)                   1
(arranged, stay, travel, agency)      1
Name: count, Length: 10482, dtype: int64